---
title: "likelihoods"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(knitr)
opts_knit$set(root.dir = "../..")
```

```{r}
source("R/default-model/helpers-tables.R")

library(fitdistrplus)
library(dplyr)
library(tidyr)
```


## specify table parameters

```{r}
params_tables <- tibble(n_tables=500,
                        nor_beta=NA,
                        nor_theta=NA,
                        param_nor_beta=1,
                        param_nor_theta=10,
                        indep_sigma=0.01,
                        seed=1234)
```


```{r}
# tables <- readRDS(paste("./data/precomputations/model-general/tables-all.rds", sep=""))
tables_path <- ("./data/default-model/tables-all.rds")
if(!file.exists(tables_path)){
  tables <- create_tables(params_tables, tables_path)
} else {
  tables <- readRDS(tables_path) %>% filter_tables(params_tables)
  if(nrow(tables)==0){
    tables <- create_tables(params_tables, tables_path)
  }
}

tables_long <- tables %>% unnest_tables() %>% dplyr::select(val, cell, cn, id)
# %>% add_column(level="none")


tables_wide <- tables_long %>% spread(key=cell, val=val) 

table_vals <- tables_wide %>% compute_cond_prob("P(C|A)") %>% rename(p_c_given_a=p)
table_vals <- table_vals %>% compute_cond_prob("P(-C|-A)") %>% mutate(p_c_given_na=1-p) %>% dplyr::select(-p)
table_vals <- table_vals %>% mutate(pc=`AC`+`-AC`, pa=`AC`+`A-C`)

table_vals <- table_vals %>% mutate(diff=(pc*pa)-`AC`)
```

## Plot models (with normal distributions) for distribution of measurements for independent networks

```{r, message=FALSE, print=FALSE,echo=FALSE}
table_vals %>% ggplot() +
  geom_density(aes(x=diff, colour=cn)) +
  facet_wrap(~cn, scales="free")

tables_ind <- table_vals %>% filter(cn=="A || C")
val_ind <- tables_ind %>% filter(!is.na(diff)) %>% pull(diff)
model1 <- fitdist(val_ind, "norm")
plot(model1)

# cn: A implies C
val_ac <- table_vals %>% filter(cn=="A implies C" & !is.na(p_c_given_a)) %>% pull(p_c_given_a)
model2 <- fitdist(val_ac, "beta")
plot(model2)

# cn: A implies -C
val_anc <- table_vals %>% filter(cn=="A implies -C" & !is.na(p_c_given_na)) %>% pull(p_c_given_na)
model3 <- fitdist(val_anc, "beta")
plot(model3)
```

## Distributions of log likelihoods

```{r}
parameters <- model1$estimate %>% as.list()

ll_ind <- table_vals %>%
            mutate(ll_ind=log(dnorm(diff, mean=parameters$mean, sd=parameters$sd)))

ll_ind %>% ggplot() +
  geom_density(aes(x=ll_ind)) +
  facet_wrap(~cn, scales="free")

ll_ac <- table_vals %>% mutate(ll_ac=log(dbeta(p_c_given_a, 10, 1)) +
                                 log(dbeta(p_c_given_na, 1, 10)))

ll_ac %>% ggplot() +
  geom_density(aes(x=ll_ac)) +
  facet_wrap(~cn, scales="free")
```







