---
title: "Model interpretation of indicative conditionals"
author: "Britta Grusdt"
date: "5/6/2019"
output: html_document
---

```{r}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r helpers, echo = FALSE}
library(tidyverse)
library(ggplot2)
source(file.path("..", "helpers.R", fsep = .Platform$file.sep))
```

# Specify parameters of model to plot

```{r}
seed <- 123
noise <- 0.03
n_tables <- 1000
```

# Geta Data

```{r}
noise_str <- as.character(noise) %>% str_replace("\\.", "_")
fn <- paste("seed-", seed, "-noise-", noise_str, "-tables-", n_tables, sep="")
result_dir <- file.path("..", "..", "data", "results", "model-general", fn,
                        fsep = .Platform$file.sep)
fn_no_bias <- file.path(result_dir, "indicative-conditionals.rds")
fn_biscuits <- file.path(result_dir, "biscuit-conditionals.rds")
fn_cp <- file.path(result_dir, "cp-conditionals.rds")

indicative_no_bias <- read_rds(fn_no_bias) %>% webppl_distrs_to_tibbles()
indicative_biscuit <- read_rds(fn_biscuits) %>% webppl_distrs_to_tibbles()
indicative_cp <- read_rds(fn_cp) %>%  webppl_distrs_to_tibbles()
```

# Interpretation of simple indicative conditionals
## Prior

```{r}
distr <- "prior"
data <- indicative_no_bias[[distr]]

data  %>% plot_cns(distr)

# ev <- data %>% expected_val(c("C"))
# print(paste('E[P(C)]:', ev))

# ev <- data %>% expected_val(c("A"))
# print(paste('E[P(A)]:', ev))

```

## Literal Listener

```{r}
distr <- "LL"
data <- indicative_no_bias[[distr]]

data  %>% plot_cns(distr)

# ev <- data %>% expected_val(c("C"))
# print(paste('E[P(C)]:', ev))

# ev <- data %>% expected_val(c("A"))
# print(paste('E[P(A)]:', ev))
```

## Pragmatic Listener


```{r}
distr <- "PL"
data <- indicative_no_bias[[distr]]

data  %>% plot_cns(distr)

# ev <- data %>% expected_val(c("C"))
# print(paste('E[P(C)]:', ev))

# ev <- data %>% expected_val(c("A"))
# print(paste('E[P(A)]:', ev))

```


# Interpretation of Biscuit conditionals
## Prior

```{r}
distr <- "prior"
data <- indicative_biscuit[[distr]]

# ev <- data %>% expected_val(c("C"))
# print(paste('E[P(C)]:', ev))
# 
# ev <- data %>% expected_val(c("A"))
# print(paste('E[P(A)]:', ev))

```

## Literal Listener

```{r}
distr <- "LL"
data <- indicative_biscuit[[distr]]

# ev <- data %>% expected_val(c("C"))
# print(paste('E[P(C)]:', ev))
# 
# ev <- data %>% expected_val(c("A"))
# print(paste('E[P(A)]:', ev))
```

## Pragmatic Listener


```{r}
distr <- "PL"
data <- indicative_biscuit[[distr]]

# ev <- data %>% expected_val(c("C"))
# print(paste('E[P(C)]:', ev))
# 
# ev <- data %>% expected_val(c("A"))
# print(paste('E[P(A)]:', ev))

```



# Interpretation of conditionals with CP-context
## Prior

```{r}
distr <- "prior"
data <- indicative_cp[[distr]]

data  %>% plot_cns(distr)

```

## Literal Listener

```{r}
distr <- "LL"
data <- indicative_cp[[distr]]

data  %>% plot_cns(distr)

```

## Pragmatic Listener


```{r}
distr <- "PL"
data <- indicative_cp[[distr]]

data  %>% plot_cns(distr)
```


