---
title: "Model interpretation of indicative conditionals"
author: "Britta Grusdt"
date: "5/6/2019"
output: html_document
---

```{r}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r helpers, echo = FALSE}
library(tidyverse)
library(ggplot2)
source("helpers.R")
```

# Get Data

```{r}
indicative_no_bias <- read_rds("../data/indicative-conditionals.rds") %>%
  rds_to_tibbles()
indicative_biscuit <- read_rds("../data/biscuit-conditionals.rds") %>%
   rds_to_tibbles()
indicative_cp <- read_rds("../data/cp-conditionals.rds") %>% rds_to_tibbles()
```

# Interpretation of simple indicative conditionals
## Prior

```{r}
distr <- "prior"
data <- indicative_no_bias[[distr]]

data  %>% plot_cns(distr)

ev <- data %>% expected_val(c("C"))
print(paste('E[P(C)]:', ev))

ev <- data %>% expected_val(c("A"))
print(paste('E[P(A)]:', ev))

```

## Literal Listener

```{r}
distr <- "LL"
data <- indicative_no_bias[[distr]]

data  %>% plot_cns(distr)

ev <- data %>% expected_val(c("C"))
print(paste('E[P(C)]:', ev))

ev <- data %>% expected_val(c("A"))
print(paste('E[P(A)]:', ev))
```

## Pragmatic Listener


```{r}
distr <- "PL"
data <- indicative_no_bias[[distr]]

data  %>% plot_cns(distr)

ev <- data %>% expected_val(c("C"))
print(paste('E[P(C)]:', ev))

ev <- data %>% expected_val(c("A"))
print(paste('E[P(A)]:', ev))

```


# Interpretation of Biscuit conditionals
## Prior

```{r}
distr <- "prior"
data <- indicative_biscuit[[distr]]

ev <- data %>% expected_val(c("C"))
print(paste('E[P(C)]:', ev))

ev <- data %>% expected_val(c("A"))
print(paste('E[P(A)]:', ev))

```

## Literal Listener

```{r}
distr <- "LL"
data <- indicative_biscuit[[distr]]

ev <- data %>% expected_val(c("C"))
print(paste('E[P(C)]:', ev))

ev <- data %>% expected_val(c("A"))
print(paste('E[P(A)]:', ev))
```

## Pragmatic Listener


```{r}
distr <- "PL"
data <- indicative_biscuit[[distr]]

ev <- data %>% expected_val(c("C"))
print(paste('E[P(C)]:', ev))

ev <- data %>% expected_val(c("A"))
print(paste('E[P(A)]:', ev))

```



# Interpretation of conditionals with CP-context
## Prior

```{r}
distr <- "prior"
data <- indicative_cp[[distr]]

data  %>% plot_cns(distr)

```

## Literal Listener

```{r}
distr <- "LL"
data <- indicative_cp[[distr]]

data  %>% plot_cns(distr)

```

## Pragmatic Listener


```{r}
distr <- "PL"
data <- indicative_cp[[distr]]

data  %>% plot_cns(distr)
```


