---
title: "p delta assertability"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
source("plot-functions.R")
source("helpers.R")
```


```{r}
RESULT_DIR <- file.path("..", "data", fsep=.Platform$file.sep)

# Default model: no bias --------------------------------------------------
fn_no_bias <- file.path(RESULT_DIR, "default-model", "results-none.rds")
data_no_bias <- read_rds(fn_no_bias)
```

```{r}
data_wide <- data_no_bias %>% spread(key=cell, val=val)# %>% adapt_bn_ids()
data_long <- data_wide %>% gather(`AC`, `AC`, `A-C`, `-AC`, `-A-C`, key=cell, val=val)

cond1 <- compute_cond_prob(data_wide, "P(C|A)")
cond2 <- compute_cond_prob(data_wide, "P(C|-A)") 

df <- data_wide %>% mutate(pca=compute_cond_prob(data_wide, "P(C|A)") %>% pull(p),
                     pcna=compute_cond_prob(data_wide, "P(C|-A)") %>% pull(p),
                     p_delta=round(pca-pcna,3),
                     p_rooij=round(p_delta/(1-pcna), 3))
df <- df %>% gather(p_delta, p_rooij, key="constraint", value="val")
```


p_delta: P(C|A) - P(C|¬A)


relative difference (p_rooij): (P(C|A) - P(C|¬A)) / (1 - P(C|¬A))


```{r}
df %>%  filter(val>0.9) %>% group_by(constraint, level) %>% summarize(sum_prob=sum(prob))
```



```{r}
df %>% filter(constraint == "p_rooij" & is.infinite(val))
```

```{r}
df %>% filter(constraint == "p_rooij" & is.na(val)) %>% group_by(level)
```

