---
title: "Figures Paper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r helpers, include=FALSE}
library(tidyverse)
library(ggplot2)
source("helpers.R")
source("plot-functions.R")
RESULT_DIR <- file.path("..", "data", "results", fsep = .Platform$file.sep)
```

## Data

```{r data, echo=TRUE}
fn_no_bias <- file.path(RESULT_DIR, "model-general", "indicative-conditionals.rds")
fn_biscuits <- file.path(RESULT_DIR, "model-general", "biscuit-conditionals.rds")
fn_cp <- file.path(RESULT_DIR, "model-general", "cp-conditionals.rds")

data_no_bias <- read_rds(fn_no_bias)
data_biscuit <- read_rds(fn_biscuits) 
data_cp <- read_rds(fn_cp)
```

## Speaker epistemic uncertainty

```{r epistemic-speaker-uncertainty-data}
data_wide <- data_no_bias %>% spread(key=cell, val=val)
pc <- marginalize(data_no_bias, c("C")) 
pa <- marginalize(data_no_bias, c("A"))

evs_all <- bind_rows(pc %>% expected_val("C"), pa %>% expected_val("A")) %>% add_column(bias="none")
evs_all

```

```{r epistemic-speaker-uncertainty, message=FALSE}
plot_marginal_prob(pa, c("A"), evs=evs_pa, save_as=file.path(RESULT_DIR, "figs", "no-bias-pa.png"))
plot_marginal_prob(pa, c("C"), evs=evs_pc, save_as=file.path(RESULT_DIR, "figs", "no-bias-pc.png"))

plot_marginal_prob(data_no_bias, "cns", save_as=file.path(RESULT_DIR, "figs", "no-bias-cns.png"))
```


## Biscuit conditionals

```{r biscuit-conditionals-data}
data_wide <- data_biscuit %>% spread(key=cell, val=val)
pc <- marginalize(data_biscuit, c("C"))
pa <- marginalize(data_biscuit, c("A"))
evs <- bind_rows(expected_val(pc, c("C")), expected_val(pa, c("A"))) %>% add_column(bias="biscuits")
evs

evs_all <- bind_rows(evs_all, evs) 
```


```{r biscuit-conditionals, message=FALSE}
plot_marginal_prob(pc, c("C"), evs=filter(evs, p=="C"), save_as=file.path(RESULT_DIR, "figs", "biscuit-pc.png"))
```


```{r conditional-perfection-data}
data_wide <- data_cp %>% spread(key=cell, val=val)
pc <- marginalize(data_cp, c("C")) 
pa <- marginalize(data_cp, c("A")) 
evs <- bind_rows(expected_val(pc, "C"), expected_val(pa, "A")) %>% add_column(bias="cp")
evs

evs_all <- bind_rows(evs_all, evs) 
```


```{r conditional-perfection, message=FALSE}
plot_marginal_prob(pa, c("A"), evs=expected_val(pa, "A"), save_as=file.path(RESULT_DIR, "figs", "cp-pa.png"))
plot_marginal_prob(pc, c("C"), evs=expected_val(pc, "C"), save_as=file.path(RESULT_DIR, "figs", "cp-pc.png"))

plot_marginal_prob(data_cp, "cns", save_as=file.path(RESULT_DIR, "figs", "cp-cns.png"))
```


```{r evs-pc, message=FALSE}
plot_evs(evs_all, marginal="C", save_as=file.path(RESULT_DIR, "figs", "evs-pc.png"))
plot_evs(evs_all, marginal="A", save_as=file.path(RESULT_DIR, "figs", "evs-pa.png"))
```


## Values of interest compared across PL/LL/prior

```{r param-sweep-data}
data <- readRDS(file.path("..", "data", "results", "model-general-all.rds"))
```


```{r values-of-interest}
df <- data %>% filter(param_nor_beta==10 & param_nor_theta==10 & model_id==1 & cost==0 & alpha==5)
```


## Values of interest depending on combination of alpha and cost

```{r param-sweep, message=FALSE}
data <- data %>% filter(seed==1234)
plot_voi_alpha_cost(data, 1, "epistemic_uncertainty", "PL")

plot_voi_alpha_cost(data, 2, "biscuits_pc", "LL")
plot_voi_alpha_cost(data, 2, "biscuits_pc", "PL")

df <- data %>% filter(key=="cp-cns" | key=="cp-bns") %>%
        filter(model_id == 1 | model_id == 3) %>%
        separate(value, c("dir", "value"), sep="_")

# value of interest considering causal nets
plot_voi_alpha_cost(df, 1, "cp-cns", "LL")
plot_voi_alpha_cost(df, 1, "cp-cns", "PL")

plot_voi_alpha_cost(df, 3, "cp-cns", "LL")
plot_voi_alpha_cost(df, 3, "cp-cns", "PL")

# value of interest considering bayes nets
plot_voi_alpha_cost(df, 1, "cp-bns", "LL")
plot_voi_alpha_cost(df, 1, "cp-bns", "PL")

plot_voi_alpha_cost(df, 3, "cp-bns", "LL")
plot_voi_alpha_cost(df, 3, "cp-bns", "PL")

```


## Douven examples
1. Sundowners
```{r sundowners, message=FALSE}
fn <- file.path(RESULT_DIR, "sundowners.rds")
data <- readRDS(fn)
data_wide <- data %>% spread(key=cell, val=val, fill = 0)

pr <- marginalize(data, c("R"))
plot_marginal_bar(pr, "R", save_as=file.path(RESULT_DIR, "figs", "sundowners-pr.png"))
```

1.1 Literal Listener distributions for each utterance

```{r, message=FALSE}
fn <- file.path(RESULT_DIR, "model-5-LL-all-utts.rds")
data <- readRDS(fn)


data_wide <- data %>% group_by(u, rowid) %>% spread(key=cell, val=val, fill=0)
bns <- data_wide %>% group_by(cn, RS, `-RS`, `-RS-W`, `R-SW`) %>% mutate(bn_id=group_indices())


for(u in bns$u %>% unique()){
  df <- bns %>% filter(u== (!! u)) %>% rename(p=bn_id) %>% add_column(level="LL")
  p <- plot_marginal_bar(df, "bns", title=u, save_as=NULL)
  print(p)
}

```


